### ISSUE TITLE
Default args cause error with node < 6.0.0

### ISSUE THREAD

**Issue by bsyk** [PredixDev/predix-fast-token#1]
When using this library with node version less than 6, this error may be seen:

```
 [App/0]      ERR /home/vcap/app/node_modules/predix-fast-token/index.js:115
 [App/0]      ERR token_utils.remoteVerify = (token, issuer, clientId, clientSecret, opts = {}) => {
 [App/0]      ERR                                                                         ^
 [App/0]      ERR SyntaxError: Unexpected token =
 [App/0]      ERR     at exports.runInThisContext (vm.js:53:16)
 [App/0]      ERR     at Module._compile (module.js:373:25)
 [App/0]      ERR     at Object.Module._extensions..js (module.js:416:10)
 [App/0]      ERR     at Module.load (module.js:343:32)
 [App/0]      ERR     at Function.Module._load (module.js:300:12)
 [App/0]      ERR     at Module.require (module.js:353:17)
 [App/0]      ERR     at require (internal/module.js:12:17)
 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/app.js:5:25)
 [App/0]      ERR     at Module._compile (module.js:409:26)
 [App/0]      ERR     at Object.Module._extensions..js (module.js:416:10)
```

**Comment by bsyk** [comment]
Fixed in v1.1.1 by commit https://github.com/PredixDev/predix-fast-token/commit/719ddd7203f841ea91a760e0dfc594e1feb6b57f
